language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

services:
  - mysql

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - mysql -u root -e "CREATE DATABASE catmash_test";

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
